### ISSUE TITLE
setup.py fails

### ISSUE THREAD

**Issue by keflavich** [keflavich/FITS_tools#5]
cc @bsipocz, can you help out?

If I try running `python setup.py install` or `develop` (commit 5fa7f6a82cd28597cbefd0670c858978631b2322), I get the following traceback:

```
$ python setup.py develop
Traceback (most recent call last):
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/configparser.py", line 843, in items
    d.update(self._sections[section])
KeyError: 'entry_points'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    entry_point_list = conf.items('entry_points')
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/configparser.py", line 846, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'entry_points'
```

[Earlier commits](c8c958d20c42fca43a1c741bdbf28b66250484f2) suffered from a different problem, which led me to update `setup.py` from `package-template`:
```
$ python setup.py develop
Updating astropy_helpers submodule with: `git submodule update -- astropy_helpers`
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    conf = config.ConfigParser()
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
```

**Comment by bsipocz** [comment]
Sure, will do it later this evening.
